/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnterprisePanel.java
 *
 * Created on Nov 23, 2011, 1:56:14 PM
 */
package vn.com.hkt.erm.enterprise.ui;

import javax.swing.JTable;

/**
 *
 * @author longnt
 */
public class EnterprisePanel extends javax.swing.JPanel {

    @Override
    public String toString() {
        return "Enterprise Base";
    }

    /** Creates new form EnterprisePanel */
    private EnterpriseCell enterpriseCell ;
    public EnterprisePanel() {
        initComponents();
        enterpriseCell = new EnterpriseCell();
        tabelEnterprise.getColumnModel().getColumn(1).setCellEditor(enterpriseCell);
         
    }

    public EnterpriseCell getEnterpriseCell() {
        return enterpriseCell;
    }

    public JTable getTabelEnterprise() {
        return tabelEnterprise;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelEnterprise = new javax.swing.JTable();

        tabelEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Tên công ty", " "},
                {"Mã công ty", " "},
                {"Công ty mẹ", " "},
                {"Giám đốc", " "},
                {"Logo", " "},
                {"Slogan", " "}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelEnterprise.setRowHeight(25);
        jScrollPane1.setViewportView(tabelEnterprise);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelEnterprise;
    // End of variables declaration//GEN-END:variables
}
