/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.com.hkt.erm.enterprise.ui;

import java.awt.Color;
import java.io.IOException;
import javax.swing.JPanel;
import vn.com.hkt.pilot.entities.Enterprise;
import vn.com.hkt.basic.api.IEnterpriseBN;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.cookies.ViewCookie;
import org.openide.util.Lookup;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.util.lookup.ServiceProvider;
import org.openide.windows.WindowManager;
import vn.com.hkt.pilot.ui.setup.StripedTableCellRenderer;
import vn.com.hkt.pilot.viewer.api.FilterCookie;
import vn.com.hkt.pilot.viewer.api.IEnterpriseViewer;
import vn.com.hkt.pilot.viewer.api.RemoveCookie;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//vn.com.hkt.erm.enterprise.ui//ListEnterprise//EN",
autostore = false)
@TopComponent.Description(preferredID = "ListEnterpriseTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "vn.com.hkt.erm.enterprise.ui.ListEnterpriseTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_ListEnterpriseAction",
preferredID = "ListEnterpriseTopComponent")
@ServiceProvider(service = IEnterpriseViewer.class)
public final class ListEnterpriseTopComponent extends TopComponent implements ActionListener, MouseListener,
        IEnterpriseViewer, ViewCookie, RemoveCookie, FilterCookie {

    private IEnterpriseBN enterpriseBN;
    private ListEnterprisePanel listEnterprisePanel = new ListEnterprisePanel();
    //private JPanel panelBasic;
    private DefaultTableModel model;
    private static int row;
    private AbstractLookup lookup;
    private InstanceContent content = new InstanceContent();

    public ListEnterpriseTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ListEnterpriseTopComponent.class, "CTL_ListEnterpriseTopComponent"));
        setToolTipText(NbBundle.getMessage(ListEnterpriseTopComponent.class, "HINT_ListEnterpriseTopComponent"));

        //panelBasic = new JPanel(new GridLayout());
        panelForm.setLayout(new GridLayout());
        panelForm.add(listEnterprisePanel);
        //panelBasic.add(listEnterprisePanel);
        listEnterprisePanel.getTableListE().addMouseListener(this);

         buttonEdit.setEnabled(false);
        buttonEdit.addActionListener(this);
        buttonExit.addActionListener(this);
        buttonHelp.addActionListener(this);
        buttonSave.addActionListener(this);
        buttonDelete.addActionListener(this);

        this.enterpriseBN = Lookup.getDefault().lookup(IEnterpriseBN.class);

        lookup = new AbstractLookup(content);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForm = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        cboTimkiem = new javax.swing.JComboBox();
        panleButton = new javax.swing.JPanel();
        buttonEdit = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        buttonHelp = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ListEnterpriseTopComponent.class, "ListEnterpriseTopComponent.jLabel1.text")); // NOI18N

        txtTimKiem.setText(org.openide.util.NbBundle.getMessage(ListEnterpriseTopComponent.class, "ListEnterpriseTopComponent.txtTimKiem.text")); // NOI18N
        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTimKiemMousePressed(evt);
            }
        });
        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });

        cboTimkiem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tên", "ID", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panleButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        org.openide.awt.Mnemonics.setLocalizedText(buttonEdit, org.openide.util.NbBundle.getMessage(ListEnterpriseTopComponent.class, "ListEnterpriseTopComponent.buttonEdit.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonSave, org.openide.util.NbBundle.getMessage(ListEnterpriseTopComponent.class, "ListEnterpriseTopComponent.buttonSave.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonExit, org.openide.util.NbBundle.getMessage(ListEnterpriseTopComponent.class, "ListEnterpriseTopComponent.buttonExit.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonHelp, org.openide.util.NbBundle.getMessage(ListEnterpriseTopComponent.class, "ListEnterpriseTopComponent.buttonHelp.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonDelete, org.openide.util.NbBundle.getMessage(ListEnterpriseTopComponent.class, "ListEnterpriseTopComponent.buttonDelete.text")); // NOI18N

        javax.swing.GroupLayout panleButtonLayout = new javax.swing.GroupLayout(panleButton);
        panleButton.setLayout(panleButtonLayout);
        panleButtonLayout.setHorizontalGroup(
            panleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panleButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panleButtonLayout.setVerticalGroup(
            panleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panleButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit)
                    .addComponent(buttonSave)
                    .addComponent(buttonDelete)
                    .addComponent(buttonExit)
                    .addComponent(buttonHelp))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        String strTim = txtTimKiem.getText().trim();

        if (cboTimkiem.getSelectedIndex() == 0) {

            String[] header = {"Tên Cty", "Mã Cty", "Cty mẹ", "Giám đốc", "Logo", "Slogan"};
            model = new DefaultTableModel(header, 0);
            List<Enterprise> list = new ArrayList<Enterprise>();
            list = enterpriseBN.filterEnterpriseByName(strTim);
            for (Enterprise bean : list) {
                String[] rows = {bean.getEnterpriseName(), bean.getEnterpriseID(), bean.getEnterpriseParent(), bean.getDirector()};
                model.addRow(rows);
            }
            listEnterprisePanel.getTableListE().setModel(model);

        } else if (cboTimkiem.getSelectedIndex() == 1) {

            String[] header = {"Tên Cty", "Mã Cty", "Cty mẹ", "Giám đốc", "Logo", "Slogan"};
            model = new DefaultTableModel(header, 0);
            List<Enterprise> list = new ArrayList<Enterprise>();
            list = enterpriseBN.filterEnterpriseByID(strTim);
            for (Enterprise bean : list) {
                String[] rows = {bean.getEnterpriseName(), bean.getEnterpriseID(), bean.getEnterpriseParent(), bean.getDirector()};
                model.addRow(rows);
            }
            listEnterprisePanel.getTableListE().setModel(model);
        }
        setupTable();
    }//GEN-LAST:event_txtTimKiemCaretUpdate

    private void txtTimKiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMousePressed
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemMousePressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox cboTimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panleButton;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    public void loadData() {
        String[] header = {"Tên Cty", "Mã Cty", "Cty mẹ", "Giám đốc", "Logo", "Slogan"};
        model = new DefaultTableModel(header, 0);
        List<Enterprise> list = new ArrayList<Enterprise>();
        list = enterpriseBN.getAllEnterprise();
        for (Enterprise bean : list) {
            String[] rows = {bean.getEnterpriseName(), bean.getEnterpriseID(), bean.getEnterpriseParent(), bean.getDirector()};
            model.addRow(rows);
        }
        listEnterprisePanel.getTableListE().setModel(model);
        setupTable();
    }

    @Override
    public void componentOpened() {
        loadData();
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void actionPerformed(ActionEvent e) {

        JButton button = (JButton) e.getSource();
        if (button == buttonExit) {
            this.close();
        }
        if (button == buttonDelete) {
            int i = listEnterprisePanel.getTableListE().getSelectedRow(); // chọn hàng để xóa
            String strID = listEnterprisePanel.getTableListE().getValueAt(i, 1).toString().trim(); // lấy ID
            Enterprise enterprise = enterpriseBN.getEnterpriseByID(strID); // Tìm kiếm Enterprise theo ID
            enterpriseBN.deleteEnterprise(enterprise);
            model.removeRow(i);
        }
        if (button == buttonEdit) {
            buttonEdit.setEnabled(false);
        }
        if (button == buttonSave) {
            String id = listEnterprisePanel.getTableListE().getValueAt(row, 1).toString().trim();
            String name = listEnterprisePanel.getTableListE().getValueAt(row, 0).toString().trim();
            String parent = listEnterprisePanel.getTableListE().getValueAt(row, 2).toString().trim();
            String director = listEnterprisePanel.getTableListE().getValueAt(row, 3).toString().trim();
            Enterprise bean = new Enterprise(id, name, parent, director);
            enterpriseBN.updateEnterprise(bean);
            this.close();
            this.open();

        }
    }

    // Xử lý click đúp lấy dữ liệu từ list sang form nhap
    public void mouseEvent(MouseEvent e) {
        int rows = listEnterprisePanel.getTableListE().getRowCount();
        int slectedRow = listEnterprisePanel.getTableListE().getSelectedRow();
        for (int i = 0; i < rows; i++) {
            if (i == slectedRow) {
                if (e.getClickCount() == 2) {
                    if (buttonEdit.isEnabled()==false) {
                        TopComponent top = WindowManager.getDefault().findTopComponent("EnterpriseCreatorTopComponent");
                        if (top != null) {
                            top.open();
                        } else {
                            JOptionPane.showMessageDialog(null, "So Sorry!");
                        }
                        TopComponent topView = WindowManager.getDefault().findTopComponent("EnterpriseViewerTopComponent");
                        if (topView != null) {
                            if(topView.isOpened()){
                                   topView.close();
                            }          
                        } else {
                            JOptionPane.showMessageDialog(null, "So Sorry!");
                        }
                        String strRow = listEnterprisePanel.getTableListE().getValueAt(i, 1).toString().trim();
                        Enterprise enterprise = enterpriseBN.getEnterpriseByID(strRow);
                        content.set(Collections.singleton(enterprise), null);
                    }
                    if (buttonEdit.isEnabled()) {
                        row = i;
                    }
                }
            }
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        mouseEvent(e);
    }

    @Override
    public void mousePressed(MouseEvent e) {
        mouseEvent(e);
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        mouseEvent(e);
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        mouseEvent(e);
    }

    @Override
    public void mouseExited(MouseEvent e) {
        mouseEvent(e);
    }

    @Override
    public JPanel getEnterpriseViewer() {
        return listEnterprisePanel;
    }

    @Override
    public Lookup getEnterpriseLookup() {
        return this.lookup;
    }

    @Override
    public void view() {
        loadData();
    }

    @Override
    public void remove() throws IOException {
        //JOptionPane.showMessageDialog(null, "Enterprise Base Called...");
        int i = listEnterprisePanel.getTableListE().getSelectedRow(); // chọn hàng để xóa
        if (i >= 0) {
            String strID = listEnterprisePanel.getTableListE().getValueAt(i, 1).toString().trim(); // lấy ID
            Enterprise enterprise = enterpriseBN.getEnterpriseByID(strID); // Tìm kiếm Enterprise theo ID
            content.set(Collections.singleton(enterprise), null);
            enterpriseBN.deleteEnterprise(enterprise);
            model.removeRow(i);
            loadData();
        }

    }

    protected void tkName(String tk) {
        String[] header = {"Tên Cty", "Mã Cty", "Cty mẹ", "Giám đốc", "Logo", "Slogan"};
        model = new DefaultTableModel(header, 0);
        List<Enterprise> list = new ArrayList<Enterprise>();
        list = enterpriseBN.filterEnterpriseByName(tk);
        if (!list.isEmpty()) {
            for (Enterprise bean : list) {
                String[] rows = {bean.getEnterpriseName(), bean.getEnterpriseID(), bean.getEnterpriseParent(), bean.getDirector()};
                model.addRow(rows);
            }
        }

        listEnterprisePanel.getTableListE().setModel(model);
        setupTable();
    }

    protected void tkID(String tk) {
        String[] header = {"Tên Cty", "Mã Cty", "Cty mẹ", "Giám đốc", "Logo", "Slogan"};
        model = new DefaultTableModel(header, 0);
        List<Enterprise> list = new ArrayList<Enterprise>();
        list = enterpriseBN.filterEnterpriseByID(tk);
        if (!list.isEmpty()) {
            for (Enterprise bean : list) {
                String[] rows = {bean.getEnterpriseName(), bean.getEnterpriseID(), bean.getEnterpriseParent(), bean.getDirector()};
                model.addRow(rows);
            }
        }

        listEnterprisePanel.getTableListE().setModel(model);
        setupTable();
    }

    @Override
    public void filterID(String tk) throws IOException {
        tkID(tk);
    }

    @Override
    public void filterName(String tk) throws IOException {
        tkName(tk);
    }

    @Override
    public String toString() {
        return "Enterprise Basic";
    }
    
    protected void setupTable() {
        StripedTableCellRenderer.installInColumn(listEnterprisePanel.getTableListE(), new Color(250, 251, 252), null, new Color(242, 242, 242), null);
    }
}
