/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.com.hkt.chart.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//vn.com.hkt.chart.ui//BieuDo//EN",
autostore = false)
@TopComponent.Description(preferredID = "BieuDoTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "vn.com.hkt.chart.ui.BieuDoTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_BieuDoAction",
preferredID = "BieuDoTopComponent")
public final class BieuDoTopComponent extends TopComponent implements ActionListener {

    public BieuDoTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(BieuDoTopComponent.class, "CTL_BieuDoTopComponent"));
        setToolTipText(NbBundle.getMessage(BieuDoTopComponent.class, "HINT_BieuDoTopComponent"));
        
        buttonNghiepvu.addActionListener(this);
        buttonThuChi.addActionListener(this);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonThuChi = new javax.swing.JButton();
        buttonNghiepvu = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(buttonThuChi, org.openide.util.NbBundle.getMessage(BieuDoTopComponent.class, "BieuDoTopComponent.buttonThuChi.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonNghiepvu, org.openide.util.NbBundle.getMessage(BieuDoTopComponent.class, "BieuDoTopComponent.buttonNghiepvu.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonExit, org.openide.util.NbBundle.getMessage(BieuDoTopComponent.class, "BieuDoTopComponent.buttonExit.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonThuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonNghiepvu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExit)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonThuChi)
                    .addComponent(buttonNghiepvu)
                    .addComponent(buttonExit))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonNghiepvu;
    private javax.swing.JButton buttonThuChi;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void actionPerformed(ActionEvent e) {
       JButton button = (JButton)e.getSource();
       if(button == buttonThuChi){
           ThuChiTopComponent tctc = new ThuChiTopComponent();
           tctc.open();
           this.close();
       }
       if(button == buttonNghiepvu){
           NghiepVuTopComponent nvtc = new NghiepVuTopComponent();
           nvtc.open();
           this.close();
       }
       if(button == buttonExit){
           this.close();
       }
    }
}
