/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListOperationPanel.java
 *
 * Created on Nov 23, 2011, 4:40:15 PM
 */
package vn.com.hkt.bom.operation.ui;

import javax.swing.JTable;

/**
 *
 * @author longnt
 */
public class ListOperationPanel extends javax.swing.JPanel {

 

    /** Creates new form ListOperationPanel */
    public ListOperationPanel() {
        initComponents();        
    }

    public JTable getTableListO() {
        return tableListO;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableListO = new javax.swing.JTable();

        tableListO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên nghiệp vụ", "Mã nghiệp vụ", "Ngày tháng năm", "Sản phẩm dịch vụ", "Công ty", "Bộ phân (Phòng)", "Người chịu trách nhiệm", "Phân loại", "Số lượng", "Đơn giá", "Tổng giá", "Đơn vị tính", "Đơn vị do"
            }
        ));
        tableListO.setSelectionBackground(new java.awt.Color(185, 205, 229));
        tableListO.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableListO.getTableHeader().setResizingAllowed(false);
        tableListO.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableListO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListO;
    // End of variables declaration//GEN-END:variables
}
