/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListPersonPanel.java
 *
 * Created on Nov 23, 2011, 3:24:01 PM
 */
package vn.com.hkt.hrm.person.ui;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author longnt
 */
public class ListPersonPanel extends javax.swing.JPanel {

    /** Creates new form ListPersonPanel */
    public ListPersonPanel() {
        initComponents();
        JComboBox cboEnterprise = new JComboBox();
        
        tableListP.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(cboEnterprise));
        
    }

    public JTable getTableListP() {
        return tableListP;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableListP = new javax.swing.JTable();

        tableListP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ (first name)",  "Tên (last name)", "Công ty", "Bộ phận", "Chức vụ", "Mã Person", "Ảnh"
            }
        ));
        jScrollPane1.setViewportView(tableListP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListP;
    // End of variables declaration//GEN-END:variables
}
