/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.com.hkt.hrm.person.ui;

import vn.com.hkt.pilot.entities.Person;
import vn.com.hkt.basic.api.IPersonBN;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//vn.com.hkt.hrm.person.ui//Person//EN",
autostore = false)
@TopComponent.Description(preferredID = "PersonTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "vn.com.hkt.hrm.person.ui.PersonTopComponent")
@ActionReference(path = "Menu/Nhập Số Liệu" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_PersonAction",
preferredID = "PersonTopComponent")
public final class PersonTopComponent extends TopComponent implements ActionListener {

    private PersonPanel personPanel = new PersonPanel();
    private IPersonBN personBN;

    public PersonTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(PersonTopComponent.class, "CTL_PersonTopComponent"));
        setToolTipText(NbBundle.getMessage(PersonTopComponent.class, "HINT_PersonTopComponent"));
        buttonEdit.setEnabled(false);
        buttonSaveDS.addActionListener(this);
        buttonEdit.addActionListener(this);
        buttonExit.addActionListener(this);
        buttonHelp.addActionListener(this);
        buttonReset.addActionListener(this);
        buttonSave.addActionListener(this);

        this.personBN = Lookup.getDefault().lookup(IPersonBN.class);
    }

    public void setPersonPanel(PersonPanel personPanel) {
        this.personPanel = personPanel;
    }

    public PersonPanel getPersonPanel() {
        return personPanel;
    }

    public JPanel getPanelForm() {
        return panelForm;
    }

    public JButton getButtonEdit() {
        return buttonEdit;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButton = new javax.swing.JPanel();
        buttonReset = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        buttonHelp = new javax.swing.JButton();
        buttonSaveDS = new javax.swing.JButton();
        panelForm = new javax.swing.JPanel();

        panelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        org.openide.awt.Mnemonics.setLocalizedText(buttonReset, org.openide.util.NbBundle.getMessage(PersonTopComponent.class, "PersonTopComponent.buttonReset.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonEdit, org.openide.util.NbBundle.getMessage(PersonTopComponent.class, "PersonTopComponent.buttonEdit.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonSave, org.openide.util.NbBundle.getMessage(PersonTopComponent.class, "PersonTopComponent.buttonSave.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonExit, org.openide.util.NbBundle.getMessage(PersonTopComponent.class, "PersonTopComponent.buttonExit.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonHelp, org.openide.util.NbBundle.getMessage(PersonTopComponent.class, "PersonTopComponent.buttonHelp.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonSaveDS, org.openide.util.NbBundle.getMessage(PersonTopComponent.class, "PersonTopComponent.buttonSaveDS.text")); // NOI18N

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSaveDS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonReset)
                    .addComponent(buttonEdit)
                    .addComponent(buttonSave)
                    .addComponent(buttonExit)
                    .addComponent(buttonHelp)
                    .addComponent(buttonSaveDS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSaveDS;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelForm;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        if (personPanel == null) {
            personPanel = new PersonPanel();
        }
        panelForm.setLayout(new GridLayout());
        panelForm.add(personPanel);
    }

    @Override
    public void componentClosed() {
        panelForm.removeAll();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton button = (JButton) e.getSource();
        ListPersonTopComponent listPersonTopComponent = new ListPersonTopComponent();

        if (button == buttonSaveDS) {
            update();
            reset();
            listPersonTopComponent.open();
            this.close();
        }
        if (button == buttonReset) {
            reset();
            buttonEdit.setEnabled(false);
            personPanel.getTabelPerson().setEnabled(true);
        }
        if (button == buttonExit) {
            this.close();
        }
        if (button == buttonSave) {
            update();
            this.close();
            this.open();
            reset();
        }
        if (button == buttonEdit) {
            buttonEdit.setEnabled(false);
            personPanel.getTabelPerson().setEnabled(true);
        }
    }

    // reset lại table mỗi khi save hoặc muốn điền mới
    public void reset() {
        personPanel.getTabelPerson().setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {"Họ (first name)", " "},
                    {"Tên (last name)", " "},
                    {"Công ty", " "},
                    {"Bộ phận", " "},
                    {"Chức vụ", " "},
                    {"Mã Person", " "},
                    {"Ảnh", " "}
                },
                new String[]{
                    "", ""
                }) {

            boolean[] canEdit = new boolean[]{
                false, true
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        personPanel.getTabelPerson().getColumnModel().getColumn(1).setCellEditor(new PersonCell());
    }

//    public void save() {
//        Person bean = null;
//
//        String namel = personPanel.getTabelPerson().getValueAt(1, 1).toString().trim();
//        String namef = personPanel.getTabelPerson().getValueAt(0, 1).toString().trim();
//        String cty = personPanel.getTabelPerson().getValueAt(2, 1).toString().trim();
//        String bophan = personPanel.getTabelPerson().getValueAt(3, 1).toString().trim();
//        String id = personPanel.getTabelPerson().getValueAt(4, 1).toString().trim();
//
//        bean = new Person(id, namef, namel, cty, bophan);
//
//        personBN.insertPerson(bean);
//
//    }
    public void update() {
        Person bean = null;

        String namef = personPanel.getTabelPerson().getValueAt(0, 1).toString().trim();
        String namel = personPanel.getTabelPerson().getValueAt(1, 1).toString().trim();
        String cty = personPanel.getTabelPerson().getValueAt(2, 1).toString().trim();
        String bophan = personPanel.getTabelPerson().getValueAt(3, 1).toString().trim();
        String chucvu = personPanel.getTabelPerson().getValueAt(4, 1).toString().trim();
        String id = personPanel.getTabelPerson().getValueAt(5, 1).toString().trim();

        bean = new Person(id, namef, namel, cty, bophan, chucvu);

        if (personPanel.getTabelPerson().getValueAt(5, 1).toString().trim().length() == 0 ){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã");
            return;
        }
        if (personPanel.getTabelPerson().getValueAt(0, 1).toString().trim().length() != 0) {
            personBN.updatePerson(bean);
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên");
        }
        
        
    }
}
