/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListDepartmentPanel.java
 *
 * Created on Nov 23, 2011, 4:00:14 PM
 */
package vn.com.hkt.erm.department.ui;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author longnt
 */
public class ListDepartmentPanel extends javax.swing.JPanel  {

    /** Creates new form ListDepartmentPanel */
    public ListDepartmentPanel() {
        initComponents();
        
        JComboBox cboEnterprise = new JComboBox();
        JComboBox cboPerson = new JComboBox();
        
        // add combobox to table
        tableListD.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(cboEnterprise));
        tableListD.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(cboPerson));
        //tableListD.addMouseListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableListD = new javax.swing.JTable();

        tableListD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên dự án", "Mã dự án", "Công ty", "Trưởng dự án", "Phân cấp", "Phòng ban mẹ","Sản phẩm dịch vụ"
            }
        ));
        jScrollPane1.setViewportView(tableListD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListD;
    // End of variables declaration//GEN-END:variables
 

    public JTable getTableListD() {
        return tableListD;
    }
 
}
