/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.com.hkt.erm.department.ui;

import java.awt.Color;
import vn.com.hkt.pilot.entities.Department;
import vn.com.hkt.basic.api.IDepartmentBN;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import vn.com.hkt.pilot.ui.setup.StripedTableCellRenderer;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//vn.com.hkt.erm.department.ui//ListDepartment//EN",
autostore = false)
@TopComponent.Description(preferredID = "ListDepartmentTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "vn.com.hkt.erm.department.ui.ListDepartmentTopComponent")
@ActionReference(path = "Menu/Kinh Doanh/Quản Lý Dự Án" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_ListDepartmentAction",
preferredID = "ListDepartmentTopComponent")
public final class ListDepartmentTopComponent extends TopComponent implements ActionListener, MouseListener {

    private ListDepartmentPanel listDepartmentPanel = new ListDepartmentPanel();
    private DefaultTableModel model;
    private IDepartmentBN departmentBN;
    private Department bean1;
    private String id;
    private String name;
    private String enter;
    private String person;
    private String parent;
    private String sp_dv;
    private static int a;

    public ListDepartmentTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ListDepartmentTopComponent.class, "CTL_ListDepartmentTopComponent"));
        setToolTipText(NbBundle.getMessage(ListDepartmentTopComponent.class, "HINT_ListDepartmentTopComponent"));

        panelForm.setLayout(new GridLayout());
        panelForm.add(listDepartmentPanel);

        listDepartmentPanel.getTableListD().addMouseListener(this);

        buttonEdit.setEnabled(false);
        buttonEdit.addActionListener(this);
        buttonExit.addActionListener(this);
        buttonHelp.addActionListener(this);
        buttonSave.addActionListener(this);
        buttonDelete.addActionListener(this);

        this.departmentBN = Lookup.getDefault().lookup(IDepartmentBN.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForm = new javax.swing.JPanel();
        panleButton = new javax.swing.JPanel();
        buttonEdit = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        buttonHelp = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        cboTimkiem = new javax.swing.JComboBox();

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        panleButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        org.openide.awt.Mnemonics.setLocalizedText(buttonEdit, org.openide.util.NbBundle.getMessage(ListDepartmentTopComponent.class, "ListDepartmentTopComponent.buttonEdit.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonSave, org.openide.util.NbBundle.getMessage(ListDepartmentTopComponent.class, "ListDepartmentTopComponent.buttonSave.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonExit, org.openide.util.NbBundle.getMessage(ListDepartmentTopComponent.class, "ListDepartmentTopComponent.buttonExit.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonHelp, org.openide.util.NbBundle.getMessage(ListDepartmentTopComponent.class, "ListDepartmentTopComponent.buttonHelp.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buttonDelete, org.openide.util.NbBundle.getMessage(ListDepartmentTopComponent.class, "ListDepartmentTopComponent.buttonDelete.text")); // NOI18N

        javax.swing.GroupLayout panleButtonLayout = new javax.swing.GroupLayout(panleButton);
        panleButton.setLayout(panleButtonLayout);
        panleButtonLayout.setHorizontalGroup(
            panleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panleButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        panleButtonLayout.setVerticalGroup(
            panleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panleButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit)
                    .addComponent(buttonSave)
                    .addComponent(buttonDelete)
                    .addComponent(buttonExit)
                    .addComponent(buttonHelp))
                .addContainerGap())
        );

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ListDepartmentTopComponent.class, "ListDepartmentTopComponent.jLabel1.text")); // NOI18N

        txtTimKiem.setText(org.openide.util.NbBundle.getMessage(ListDepartmentTopComponent.class, "ListDepartmentTopComponent.txtTimKiem.text")); // NOI18N
        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTimKiemMousePressed(evt);
            }
        });
        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });

        cboTimkiem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tên", "ID", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        String strTim = txtTimKiem.getText().trim();
        if (cboTimkiem.getSelectedIndex() == 0) {
            String[] header = {"Tên dự án", "Mã dự án", "Công ty", "Trưởng dự án", "Phấn cấp", "Phòng ban mẹ","Sản phẩm dịch vụ",};
            model = new DefaultTableModel(header, 0);
            List<Department> list = new ArrayList<Department>();
            list = departmentBN.filterDepartmentByName(strTim);
            for (Department bean : list) {
                String[] rows = {bean.getDepartmentName(), bean.getDepartmentID(), bean.getEnterpriseID(), bean.getPersonID()," ", bean.getDepartmentParent(), bean.getProductID()};
                model.addRow(rows);
            }
            listDepartmentPanel.getTableListD().setModel(model);
        } else if (cboTimkiem.getSelectedIndex() == 1) {
            String[] header = {"Tên dự án", "Mã dự án", "Công ty", "Trưởng dự án", "Phấn cấp", "Phòng ban mẹ", "Sản phẩm dịch vụ"};
            model = new DefaultTableModel(header, 0);
            List<Department> list = new ArrayList<Department>();
            list = departmentBN.filterDepartmentByID(strTim);
            for (Department bean : list) {
                String[] rows = {bean.getDepartmentName(), bean.getDepartmentID(), bean.getEnterpriseID(), bean.getPersonID()," ", bean.getDepartmentParent(), bean.getProductID()};
                model.addRow(rows);
            }
            listDepartmentPanel.getTableListD().setModel(model);
            
        }
        setupTable();
    }//GEN-LAST:event_txtTimKiemCaretUpdate

    private void txtTimKiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMousePressed
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemMousePressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox cboTimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panleButton;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    public void loadData() {
        String[] header = {"Tên dự án", "Mã dự án", "Công ty", "Trưởng dự án", "Phấn cấp", "Phòng ban mẹ","Sản phẩm dịch vụ"};
        model = new DefaultTableModel(header, 0);

        List<Department> list = new ArrayList<Department>();
        list = departmentBN.getAllDepartment();

        for (Department bean : list) {
            String[] rows = {bean.getDepartmentName(), bean.getDepartmentID(), bean.getEnterpriseID(), bean.getPersonID()," ", bean.getDepartmentParent(),bean.getProductID()};
            model.addRow(rows);
        }

        listDepartmentPanel.getTableListD().setModel(model);
        setupTable();
    }

    @Override
    public void componentOpened() {
        loadData();
     
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    public void mouseEvent(MouseEvent e) {
        int rows = listDepartmentPanel.getTableListD().getRowCount();
        int slectedRow = listDepartmentPanel.getTableListD().getSelectedRow();
        DepartmentTopComponent departmentTopComponent = new DepartmentTopComponent();
        for (int i = 0; i < rows; i++) {
            if (i == slectedRow) {
                if (e.getClickCount() == 2) {
                    if (buttonEdit.isEnabled()==false) {
                        String strRow = listDepartmentPanel.getTableListD().getValueAt(i, 1).toString().trim();
                        Department department = departmentBN.getDepartmentByID(strRow);
                        departmentTopComponent.getDepartmentPanel().getTableD().setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][]{
                                    {"Tên dự án", department.getDepartmentName()},
                                    {"Mã dự án", department.getDepartmentID()},
                                    {"Công ty", department.getEnterpriseID()},
                                    {"Trưởng dự án", department.getPersonID()},
                                    {"Phân cấp", " "},
                                    {"Phòng ban mẹ", department.getDepartmentParent()},
                                    {"Sản phẩm dịch vụ", department.getProductID()}
                                },
                                new String[]{
                                    "", ""
                                }) {

                            boolean[] canEdit = new boolean[]{
                                false, true
                            };

                            @Override
                            public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                            }
                        });
                        DepartmentCell departmentCell = new DepartmentCell();
                        departmentCell.getTxtNameD().setText(department.getDepartmentName());
                        departmentCell.getTxtIdD().setText(department.getDepartmentID());

                        departmentTopComponent.getDepartmentPanel().getTableD().getColumnModel().getColumn(1).setCellEditor(departmentCell);
                        departmentTopComponent.getDepartmentPanel().getTableD().setEnabled(false);
                        departmentTopComponent.getPanelForm().removeAll();
                        departmentTopComponent.getPanelForm().add(departmentTopComponent.getDepartmentPanel());
                        departmentTopComponent.getButtonEdit().setEnabled(true);
                        departmentTopComponent.open();
                        this.close();
                    }
                    if (buttonEdit.isEnabled()) {
                        a = i;
                    }
                    setupTable();
                }
            }

        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton button = (JButton) e.getSource();
        if (button == buttonExit) {
            this.close();
        }

        if (button == buttonDelete) {
            int i = listDepartmentPanel.getTableListD().getSelectedRow();
            String strRow = listDepartmentPanel.getTableListD().getValueAt(i, 1).toString().trim();
            Department department = departmentBN.getDepartmentByID(strRow);
            if (departmentBN.deleteDepartment(department)) {
                model.removeRow(i);
            } else {
                JOptionPane.showMessageDialog(null, "Delete Failed!");
            }

        }
        if (button == buttonSave) {

            id = listDepartmentPanel.getTableListD().getValueAt(a, 1).toString().trim();
            name = listDepartmentPanel.getTableListD().getValueAt(a, 0).toString().trim();
            enter = listDepartmentPanel.getTableListD().getValueAt(a, 2).toString().trim();
            person = listDepartmentPanel.getTableListD().getValueAt(a, 3).toString().trim();
            parent = listDepartmentPanel.getTableListD().getValueAt(a, 5).toString().trim();
            sp_dv=listDepartmentPanel.getTableListD().getValueAt(a, 6).toString().trim();
            bean1 = new Department(id, name, enter, person, parent,sp_dv);
            departmentBN.updateDepartment(bean1);
            this.close();
            this.open();
        }
        if (button == buttonEdit) {
            buttonEdit.setEnabled(false);
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        mouseEvent(e);
    }

    @Override
    public void mousePressed(MouseEvent e) {
        mouseEvent(e);
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        mouseEvent(e);
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        mouseEvent(e);
    }

    @Override
    public void mouseExited(MouseEvent e) {
        mouseEvent(e);
    }
    
    protected void setupTable(){
        StripedTableCellRenderer.installInColumn(listDepartmentPanel.getTableListD(), new Color(250, 251, 252), null, new Color(242, 242, 242),null);
    }
}
