/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.com.hkt.commons.gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import vn.com.hkt.commons.api.IBaseData;
import vn.com.hkt.commons.init.InitData;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//vn.com.hkt.commons.gui//CreateNewData//EN",
autostore = false)
@TopComponent.Description(preferredID = "CreateNewDataTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "vn.com.hkt.commons.gui.CreateNewDataTopComponent")
@ActionReference(path = "Menu/File/Tạo dữ liệu mẫu" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_CreateNewDataAction",
preferredID = "CreateNewDataTopComponent")
public final class CreateNewDataTopComponent extends TopComponent {

    private InitData initData;
    private String filePath;
    private IBaseData data;

    public CreateNewDataTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(CreateNewDataTopComponent.class, "CTL_CreateNewDataTopComponent"));
        setToolTipText(NbBundle.getMessage(CreateNewDataTopComponent.class, "HINT_CreateNewDataTopComponent"));
        initData = new InitData();
        data = Lookup.getDefault().lookup(IBaseData.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ckbAccount = new javax.swing.JCheckBox();
        btnChooseFile = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblMessenger = new javax.swing.JLabel();
        ckbDepartment = new javax.swing.JCheckBox();
        ckbEnterprise = new javax.swing.JCheckBox();
        ckbOperation = new javax.swing.JCheckBox();
        ckbPerson = new javax.swing.JCheckBox();
        ckbProduct = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(ckbAccount, org.openide.util.NbBundle.getMessage(CreateNewDataTopComponent.class, "CreateNewDataTopComponent.ckbAccount.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnChooseFile, org.openide.util.NbBundle.getMessage(CreateNewDataTopComponent.class, "CreateNewDataTopComponent.btnChooseFile.text_1")); // NOI18N
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnCreate, org.openide.util.NbBundle.getMessage(CreateNewDataTopComponent.class, "CreateNewDataTopComponent.btnCreate.text_1")); // NOI18N
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblMessenger, org.openide.util.NbBundle.getMessage(CreateNewDataTopComponent.class, "CreateNewDataTopComponent.lblMessenger.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ckbDepartment, org.openide.util.NbBundle.getMessage(CreateNewDataTopComponent.class, "CreateNewDataTopComponent.ckbDepartment.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ckbEnterprise, org.openide.util.NbBundle.getMessage(CreateNewDataTopComponent.class, "CreateNewDataTopComponent.ckbEnterprise.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ckbOperation, org.openide.util.NbBundle.getMessage(CreateNewDataTopComponent.class, "CreateNewDataTopComponent.ckbOperation.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ckbPerson, org.openide.util.NbBundle.getMessage(CreateNewDataTopComponent.class, "CreateNewDataTopComponent.ckbPerson.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ckbProduct, org.openide.util.NbBundle.getMessage(CreateNewDataTopComponent.class, "CreateNewDataTopComponent.ckbProduct.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseFile)
                    .addComponent(lblMessenger)
                    .addComponent(btnCreate)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbAccount)
                            .addComponent(ckbDepartment)
                            .addComponent(ckbEnterprise))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbProduct)
                            .addComponent(ckbPerson)
                            .addComponent(ckbOperation)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ckbOperation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbPerson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbProduct))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnChooseFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMessenger)
                        .addGap(6, 6, 6)
                        .addComponent(ckbAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbDepartment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbEnterprise)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
// TODO add your handling code here:
    if (filePath == null) {
        JOptionPane.showMessageDialog(null, "You have not chosen file path!");
        return;
    }
    data.createXMLFile();
    if (ckbAccount.isSelected()) {
        initData.initAccount();
    }
    if (ckbDepartment.isSelected()) {
        initData.initDepartment();
    }
    if (ckbEnterprise.isSelected()) {
        initData.initEnterprise();
    }
    if (ckbOperation.isSelected()) {
        initData.initOperation();
    }
    if (ckbPerson.isSelected()) {
        initData.initPerson();
    }
    if (ckbProduct.isSelected()) {
        initData.initProduct();
    }
    JOptionPane.showMessageDialog(null, "Create Successfully");
}//GEN-LAST:event_btnCreateActionPerformed

private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
// TODO add your handling code here:
    JFileChooser fileChooser = new JFileChooser("C:/Users/Admin/Desktop");
    fileChooser.setVisible(true);
    fileChooser.showOpenDialog(this);
    File file = fileChooser.getSelectedFile();
    if (file == null) {
        return;
    }
    if (file.getPath().endsWith("xls")) {
        filePath = file.getPath();
        lblMessenger.setText("You chose file excel: " + filePath);
        initData.setPathFileExcel(filePath);
    }
}//GEN-LAST:event_btnChooseFileActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnCreate;
    private javax.swing.JCheckBox ckbAccount;
    private javax.swing.JCheckBox ckbDepartment;
    private javax.swing.JCheckBox ckbEnterprise;
    private javax.swing.JCheckBox ckbOperation;
    private javax.swing.JCheckBox ckbPerson;
    private javax.swing.JCheckBox ckbProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMessenger;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
