/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExtensionListEnterprisePanel.java
 *
 * Created on Dec 22, 2011, 10:05:20 AM
 */
package vn.com.hkt.ui.panel;

import javax.swing.JTable;

/**
 *
 * @author longnt
 */
public class ExtensionListEnterprisePanel extends javax.swing.JPanel {

    /** Creates new form ExtensionListEnterprisePanel */
    public ExtensionListEnterprisePanel() {
        initComponents();
    }

    public JTable getTablleListExtensionE() {
        return tablleListExtensionE;
    }

    @Override
    public String toString() {
        return "Enterprise Extension";
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablleListExtensionE = new javax.swing.JTable();

        tablleListExtensionE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Địa chỉ", "Tell", "Fax", "Email", "Web"
            }
        ));
        jScrollPane1.setViewportView(tablleListExtensionE);
        tablleListExtensionE.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ExtensionListEnterprisePanel.class, "ExtensionListEnterprisePanel.tablleListExtensionE.columnModel.title0")); // NOI18N
        tablleListExtensionE.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ExtensionListEnterprisePanel.class, "ExtensionListEnterprisePanel.tablleListExtensionE.columnModel.title1")); // NOI18N
        tablleListExtensionE.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(ExtensionListEnterprisePanel.class, "ExtensionListEnterprisePanel.tablleListExtensionE.columnModel.title2")); // NOI18N
        tablleListExtensionE.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(ExtensionListEnterprisePanel.class, "ExtensionListEnterprisePanel.tablleListExtensionE.columnModel.title3")); // NOI18N
        tablleListExtensionE.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(ExtensionListEnterprisePanel.class, "ExtensionListEnterprisePanel.tablleListExtensionE.columnModel.title4")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablleListExtensionE;
    // End of variables declaration//GEN-END:variables
}
