/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExtensionEnterprisePanel.java
 *
 * Created on Dec 21, 2011, 4:35:59 PM
 */
package vn.com.hkt.ui.panel;

import javax.swing.JTable;

/**
 *
 * @author longnt
 */
public class ExtensionEnterprisePanel extends javax.swing.JPanel {

    /** Creates new form ExtensionEnterprisePanel */
    public ExtensionEnterprisePanel() {
        initComponents();
    }

    public JTable getTableExtensionE() {
        return tableExtensionE;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableExtensionE = new javax.swing.JTable();

        tableExtensionE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Địa chỉ", " ", " ", " "},
                {"Tell", " ", "Fax", " "},
                {"Email", " ", "Web", " "}
            },
            new String [] {
                "", "",  "", ""
            }
        ));
        tableExtensionE.setRowHeight(25);
        jScrollPane1.setViewportView(tableExtensionE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableExtensionE;
    // End of variables declaration//GEN-END:variables
}
